// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Pong pong
//
// swagger:model Pong
type Pong string

// Validate validates this pong
func (m Pong) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pong based on context it is used
func (m Pong) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
