// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ramanavelineni/semctl/pkg/semapi/client/authentication"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/integration"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/inventory"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/key_store"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/operations"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/project"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/repository"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/schedule"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/task"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/template"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/user"
	"github.com/ramanavelineni/semctl/pkg/semapi/client/variable_group"
)

// Default semapi HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https", "ws", "wss"}

// NewHTTPClient creates a new semapi HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Semapi {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new semapi HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Semapi {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new semapi client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Semapi {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Semapi)
	cli.Transport = transport
	cli.Authentication = authentication.New(transport, formats)
	cli.Integration = integration.New(transport, formats)
	cli.Inventory = inventory.New(transport, formats)
	cli.KeyStore = key_store.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Project = project.New(transport, formats)
	cli.Repository = repository.New(transport, formats)
	cli.Schedule = schedule.New(transport, formats)
	cli.Task = task.New(transport, formats)
	cli.Template = template.New(transport, formats)
	cli.User = user.New(transport, formats)
	cli.VariableGroup = variable_group.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Semapi is a client for semapi
type Semapi struct {
	Authentication authentication.ClientService

	Integration integration.ClientService

	Inventory inventory.ClientService

	KeyStore key_store.ClientService

	Operations operations.ClientService

	Project project.ClientService

	Repository repository.ClientService

	Schedule schedule.ClientService

	Task task.ClientService

	Template template.ClientService

	User user.ClientService

	VariableGroup variable_group.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Semapi) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Authentication.SetTransport(transport)
	c.Integration.SetTransport(transport)
	c.Inventory.SetTransport(transport)
	c.KeyStore.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Project.SetTransport(transport)
	c.Repository.SetTransport(transport)
	c.Schedule.SetTransport(transport)
	c.Task.SetTransport(transport)
	c.Template.SetTransport(transport)
	c.User.SetTransport(transport)
	c.VariableGroup.SetTransport(transport)
}
