// Code generated by go-swagger; DO NOT EDIT.

package schedule

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/ramanavelineni/semctl/pkg/semapi/models"
)

// GetProjectProjectIDSchedulesReader is a Reader for the GetProjectProjectIDSchedules structure.
type GetProjectProjectIDSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectProjectIDSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectProjectIDSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /project/{project_id}/schedules] GetProjectProjectIDSchedules", response, response.Code())
	}
}

// NewGetProjectProjectIDSchedulesOK creates a GetProjectProjectIDSchedulesOK with default headers values
func NewGetProjectProjectIDSchedulesOK() *GetProjectProjectIDSchedulesOK {
	return &GetProjectProjectIDSchedulesOK{}
}

// GetProjectProjectIDSchedulesOK describes a response with status code 200, with default header values.
//
// list of schedules (includes tpl_name)
type GetProjectProjectIDSchedulesOK struct {
	Payload []*models.Schedule
}

// IsSuccess returns true when this get project project Id schedules o k response has a 2xx status code
func (o *GetProjectProjectIDSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get project project Id schedules o k response has a 3xx status code
func (o *GetProjectProjectIDSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get project project Id schedules o k response has a 4xx status code
func (o *GetProjectProjectIDSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get project project Id schedules o k response has a 5xx status code
func (o *GetProjectProjectIDSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get project project Id schedules o k response a status code equal to that given
func (o *GetProjectProjectIDSchedulesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get project project Id schedules o k response
func (o *GetProjectProjectIDSchedulesOK) Code() int {
	return 200
}

func (o *GetProjectProjectIDSchedulesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/schedules][%d] getProjectProjectIdSchedulesOK %s", 200, payload)
}

func (o *GetProjectProjectIDSchedulesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /project/{project_id}/schedules][%d] getProjectProjectIdSchedulesOK %s", 200, payload)
}

func (o *GetProjectProjectIDSchedulesOK) GetPayload() []*models.Schedule {
	return o.Payload
}

func (o *GetProjectProjectIDSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
