// Code generated by go-swagger; DO NOT EDIT.

package schedule

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetProjectProjectIDSchedulesParams creates a new GetProjectProjectIDSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectProjectIDSchedulesParams() *GetProjectProjectIDSchedulesParams {
	return NewGetProjectProjectIDSchedulesParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetProjectProjectIDSchedulesParamsWithTimeout creates a new GetProjectProjectIDSchedulesParams object
// with the ability to set a timeout on a request.
func NewGetProjectProjectIDSchedulesParamsWithTimeout(timeout time.Duration) *GetProjectProjectIDSchedulesParams {
	return &GetProjectProjectIDSchedulesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetProjectProjectIDSchedulesParamsWithContext creates a new GetProjectProjectIDSchedulesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDSchedulesParams].
func NewGetProjectProjectIDSchedulesParamsWithContext(ctx context.Context) *GetProjectProjectIDSchedulesParams {
	return &GetProjectProjectIDSchedulesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetProjectProjectIDSchedulesParamsWithHTTPClient creates a new GetProjectProjectIDSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectProjectIDSchedulesParamsWithHTTPClient(client *http.Client) *GetProjectProjectIDSchedulesParams {
	return &GetProjectProjectIDSchedulesParams{
		HTTPClient: client,
	}
}

/*
GetProjectProjectIDSchedulesParams contains all the parameters to send to the API endpoint

	for the get project project ID schedules operation.

	Typically these are written to a http.Request.
*/
type GetProjectProjectIDSchedulesParams struct {

	// ProjectID.
	//
	// Project ID
	ProjectID int64

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get project project ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDSchedulesParams) WithDefaults() *GetProjectProjectIDSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project project ID schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectProjectIDSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) WithTimeout(timeout time.Duration) *GetProjectProjectIDSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get project project ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDSchedulesParams].
func (o *GetProjectProjectIDSchedulesParams) WithContext(ctx context.Context) *GetProjectProjectIDSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project project ID schedules params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetProjectProjectIDSchedulesParams].
func (o *GetProjectProjectIDSchedulesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) WithHTTPClient(client *http.Client) *GetProjectProjectIDSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) WithProjectID(projectID int64) *GetProjectProjectIDSchedulesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get project project ID schedules params.
func (o *GetProjectProjectIDSchedulesParams) SetProjectID(projectID int64) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetProjectProjectIDSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", conv.FormatInteger(o.ProjectID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
