// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDebugGcParams creates a new PostDebugGcParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDebugGcParams() *PostDebugGcParams {
	return &PostDebugGcParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDebugGcParamsWithTimeout creates a new PostDebugGcParams object
// with the ability to set a timeout on a request.
func NewPostDebugGcParamsWithTimeout(timeout time.Duration) *PostDebugGcParams {
	return &PostDebugGcParams{
		timeout: timeout,
	}
}

// NewPostDebugGcParamsWithContext creates a new PostDebugGcParams object
// with the ability to set a context for a request.
func NewPostDebugGcParamsWithContext(ctx context.Context) *PostDebugGcParams {
	return &PostDebugGcParams{
		Context: ctx,
	}
}

// NewPostDebugGcParamsWithHTTPClient creates a new PostDebugGcParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDebugGcParamsWithHTTPClient(client *http.Client) *PostDebugGcParams {
	return &PostDebugGcParams{
		HTTPClient: client,
	}
}

/*
PostDebugGcParams contains all the parameters to send to the API endpoint

	for the post debug gc operation.

	Typically these are written to a http.Request.
*/
type PostDebugGcParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post debug gc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDebugGcParams) WithDefaults() *PostDebugGcParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post debug gc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDebugGcParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post debug gc params
func (o *PostDebugGcParams) WithTimeout(timeout time.Duration) *PostDebugGcParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post debug gc params
func (o *PostDebugGcParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post debug gc params
func (o *PostDebugGcParams) WithContext(ctx context.Context) *PostDebugGcParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post debug gc params
func (o *PostDebugGcParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post debug gc params
func (o *PostDebugGcParams) WithHTTPClient(client *http.Client) *PostDebugGcParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post debug gc params
func (o *PostDebugGcParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostDebugGcParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
