// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostDebugGcReader is a Reader for the PostDebugGc structure.
type PostDebugGcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDebugGcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPostDebugGcNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /debug/gc] PostDebugGc", response, response.Code())
	}
}

// NewPostDebugGcNoContent creates a PostDebugGcNoContent with default headers values
func NewPostDebugGcNoContent() *PostDebugGcNoContent {
	return &PostDebugGcNoContent{}
}

/*
PostDebugGcNoContent describes a response with status code 204, with default header values.

Successful "OK" reply
*/
type PostDebugGcNoContent struct {
}

// IsSuccess returns true when this post debug gc no content response has a 2xx status code
func (o *PostDebugGcNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post debug gc no content response has a 3xx status code
func (o *PostDebugGcNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post debug gc no content response has a 4xx status code
func (o *PostDebugGcNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post debug gc no content response has a 5xx status code
func (o *PostDebugGcNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post debug gc no content response a status code equal to that given
func (o *PostDebugGcNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post debug gc no content response
func (o *PostDebugGcNoContent) Code() int {
	return 204
}

func (o *PostDebugGcNoContent) Error() string {
	return fmt.Sprintf("[POST /debug/gc][%d] postDebugGcNoContent", 204)
}

func (o *PostDebugGcNoContent) String() string {
	return fmt.Sprintf("[POST /debug/gc][%d] postDebugGcNoContent", 204)
}

func (o *PostDebugGcNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
